### ISSUE TITLE
Spurious "Session Stopped" from Whitebeet to EVSE host

### ISSUE THREAD

**Issue by zacharyalutz** [Sevenstax/FreeV2G#89] opened 2022-09-27 15:33 UTC
## Setup
Platform: **EVSE**
Firmware Version: **V02_00_01**
Host Controller Interface: **Ethernet**
Host Implemention:  **Own Implementation**
Vehicle Make: **Rivian**

## Description
After >50min of otherwise normal DC fast charging session, Whitebeet reports "Session Stopped" with a closure type of "terminate" thru the V2G service ```c0 27 8c 00 00 01 00 c8 c1```  but the vehicle never sent a _Session Stop Request_. See line 135015 of attached wireshark log.

## To reproduce
Not really sure how to reproduce this because I have no way of knowing what events can programmatically cause Whitebeet to send a "Session Stopped" message, since I don't have access to the source files. My only suggestion is to run multiple charging sessions, perhaps with a Rivian? Not sure that this is unique to Rivian tho..

## Expected behavior
I would expect Whitebeet to report "Session Stopped" on the EVSE host interface if and only if one of the following events have occurred:
* Whitebeet receives a Session Stop Request from EV
* Whitebeet detects a state transition on Control Pilot, viz C-->B/A

## Logs
[rivian-spurious-session-stop.pcapng.gz](https://github.com/Sevenstax/FreeV2G/files/9657296/rivian-spurious-session-stop.pcapng.gz)

**Comment by jpo-stx** [comment] 2022-10-04 10:47
Hi @zacharyalutz ,

have you applied any filters to the wireshark log? I cannot see any SYN, ACK and FIN TCP frames in your log, which would be helpful for further analysis.

In the last part of the sequence the EV always sends a new current demand request about ~100ms after it has received the last current demand response message. But 200ms after the Whitebeet has sent the last response message the session stopped status message is sent. Now it would be interesting which side is closing the TCP connection.

**Comment by zacharyalutz** [comment] 2022-10-04 14:52
I applied the following wireshark filter: ```eth.type == 0x6003 || v2gmsg || homeplug-av || v2gtp || seccdp```

**Comment by jpo-stx** [comment] 2022-10-04 15:07
This filter will only show tcp packets with v2gtp payload.

Can you remove the v2gmsg and v2gtp filters?

You can also filter for the mac address of a whitebeet with `eth.addr[0:3] == c4:93:00`

**Comment by zacharyalutz** [comment] 2022-10-04 15:20
unfortunately I selected "Export Specified Packets" when I saved the file on account of its size. This is all I have from the session in question :/

**Comment by jpo-stx** [comment] 2022-10-04 16:18
Any chance to capture a new log?

The communication seems to be OK and I would assume that the EV decides somehow to close the connection? EVSE should only stop the TCP connection if stop listen command is sent from the host.

**Comment by zacharyalutz** [comment] 2022-10-12 19:41
I have *not* been able to capture this behavior again.

I wonder, is it possible that Whitebeet is shutting down the session? Does Whitebeet have a watchdog function that will close the session if either EV/EVSE takes too long to respond? I do not believe our host platform is shutting down the session with a "stop listen" command, rather, the Whitebeet is reporting "session stopped" to the host. I would imagine that this would happen only under a few conditions:

- a Session Stop Request from EV
- emergency shutdown
- a communication timeout, initated by Whitebeet itself?

Let me know what you think, and I will keep trying to reproduce. Thanks!

**Comment by jpo-stx** [comment] 2022-10-17 12:40
There is an internal timeout of 60s for the next request message of the EV. The timer starts when the last response message was sent to the EV. But since the session is stopped within a second this timer is not the cause.

It would be really interesting to see how is closing the connection, which would be indicated by the TCP FIN flag.

Are you also monitoring the control pilot? Is the EV changing the state to B before or after the connection is closed?

**Comment by lho-stx** [comment] 2022-12-23 10:55
This issue is closed due to inactivity. If the issue is still present, please re-open the issue!

**Closed by lho-stx** 2022-12-23 10:55 UTC
Labels: EVSE
