### ISSUE TITLE
Spi Data Exchange frame Identifier error after some time 

### ISSUE THREAD

**Issue by xuanlanghuang** [Sevenstax/FreeV2G#322] opened 2024-06-05 15:44 UTC
**Before you post**
- [x] I confirm that I've read the [guide on how to post issues](https://github.com/Sevenstax/FreeV2G/issues/304)
- [x] I confirm that I've consulted the [wiki](https://github.com/Sevenstax/FreeV2G/wiki) about my issue

**Your Setup**
Platform: PEV
Firmware Version: i.e. V01_00_07
Host Controller Interface: SPI
Host:  Own Implementation

**Describe the bug**
Spi Data Exchange frame Identifier error after some time 

**To Reproduce**
This happen consistently after some time the PEV WB is running, the identifier of data exchange has a 0xD5 at the beginning and the whole message is shifted, this cause our logic to think the WB is out of sync and have an incomplete message
the spi baudrate  is 7,000,000

**Logs**
![image](https://github.com/Sevenstax/FreeV2G/assets/109241565/518645bc-8724-4c6e-bca1-367efcac9b0a)

[spi-out-of-sync.zip](https://github.com/user-attachments/files/15593044/spi-out-of-sync.zip)
(out of sync at 64.33s for the "wb_outofsync-64-33s" , and 2.188s for "wb_outofsync2-2-188s")

**Additional context**

**Comment by lho-stx** [comment] 2024-06-14 07:10
Hey @xuanlanghuang,

I tried to reproduce your issue, but had no luck. Are you using the WHITE Beet carrier board or do you have a custom Hardware? If you are using WHITE Beet PI carrier board, what is your host device? Do you experience glitches in any other part of the communication? I want to rule out the possibility that it is a problem related to the hardware (e.g. distorted signals). But if this is happening in the setup bytes only, then I need to investigate further. Maybe I'll send you a special debug firmware, because I am not able to reproduce the issue.

Best regards,
lho

**Comment by lho-stx** [comment] 2024-06-14 07:36
Hey @xuanlanghuang,

I checked the logs again and had a look into the timing. Between the CS going low and the first transmission are 10.5μs. In the WHITE Beet manual chapter 9.2.6 the minimum delay time is 20μs.

![2024-06-14-093540_1920x1080_scrot](https://github.com/Sevenstax/FreeV2G/assets/103272216/cb93e7c4-5ef1-4354-8e59-4f380786d3d6)

Please adapt your host implementation to wait at least 20μs before starting data transmission after asserting the CS line.

Best regards,
lho

**Comment by xuanlanghuang** [comment] 2024-07-17 21:17
Hi, 

I managed to add the delay before the spi send.

But during our testing, we found an edge case where the tx-pending go up during a request size exchange and data exchange, this will cause the WB to not have a zero size exchange.
![image](https://github.com/user-attachments/assets/4f1da981-e657-410e-88e4-1cde749cba6d)

What is the correct way to handle this situation?
[txpendingHigh-1ms.zip](https://github.com/user-attachments/files/16274847/txpendingHigh-1ms.zip)

Thanks you.

**Comment by lho-stx** [comment] 2024-07-18 05:12
Hey @xuanlanghuang,

I will check the log files!

Best regards,
lho

**Comment by xuanlanghuang** [comment] 2024-07-29 14:36
Is info@sevenstax.de the right contact email? I don't see a contact form from the website.

Thanks,

**Comment by lho-stx** [comment] 2024-07-29 14:41
Yes!

**Comment by lho-stx** [comment] 2024-08-06 05:56
Closing this issue. We will work on it with the customer directly!

**Closed by lho-stx** 2024-08-06 05:56 UTC
Labels: setup
